"""changed password hash to not null

Revision ID: 405f630645e2
Revises: 6206b259ddf7
Create Date: 2025-06-22 12:26:57.368554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405f630645e2'
down_revision = '6206b259ddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
